import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import Script from "next/script";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <head>
        <link rel="shortcut icon" type="image/x-icon" href="/assets/images/fav.svg" />
        {/* animate css */}
        <link rel="stylesheet" href="/assets/css/plugins/animate.min.css" />
        {/* fontawesome 6.4.2 */}
        <link rel="stylesheet" href="/assets/css/plugins/fontawesome.min.css" />
        {/* bootstrap min css */}
        <link rel="stylesheet" href="/assets/css/vendor/bootstrap.min.css" />
        {/* swiper Css 10.2.0 */}
        <link rel="stylesheet" href="/assets/css/plugins/swiper.min.css" />
        {/* Bootstrap 5.0.2 */}
        <link rel="stylesheet" href="/assets/css/vendor/magnific-popup.css" />
        {/* metismenu scss */}
        <link rel="stylesheet" href="/assets/css/vendor/metismenu.css" />
        {/* nice select js */}
        <link rel="stylesheet" href="/assets/css/plugins/nice-select.css" />
        <link rel="stylesheet" href="/assets/css/plugins/jquery-ui.css" />
        {/* custom style css */}
        <link rel="stylesheet" href="/assets/css/style.css" />
      </head>
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        {children}
        <Script src="/assets/js/vendor/jquery.min.js" strategy="beforeInteractive" />
        <Script src="/assets/js/plugins/bootstrap.min.js" strategy="lazyOnload" />
        <Script src="/assets/js/vendor/jquery-ui.js" strategy="lazyOnload" />
        <Script src="/assets/js/vendor/waw.js" strategy="lazyOnload" />
        <Script src="/assets/js/vendor/metismenu.js" strategy="lazyOnload" />
        <Script src="/assets/js/vendor/magnifying-popup.js" strategy="lazyOnload" />
        <Script src="/assets/js/plugins/swiper.js" strategy="beforeInteractive" />
        <Script src="/assets/js/plugins/counterup.js" strategy="lazyOnload" />
        <Script src="/assets/js/vendor/waypoint.js" strategy="lazyOnload" />
        <Script src="/assets/js/plugins/isotop.js" strategy="lazyOnload" />
        <Script src="/assets/js/plugins/imagesloaded.pkgd.min.js" strategy="lazyOnload" />
        <Script src="/assets/js/plugins/sticky-sidebar.js" strategy="lazyOnload" />
        <Script src="/assets/js/plugins/resize-sensor.js" strategy="lazyOnload" />
        <Script src="/assets/js/plugins/twinmax.js" strategy="lazyOnload" />
        <Script src="/assets/js/plugins/contact.form.js" strategy="lazyOnload" />
        <Script src="/assets/js/plugins/nice-select.min.js" strategy="lazyOnload" />
        <Script src="/assets/js/main.js" strategy="lazyOnload" />
      </body>
    </html>
  );
}
